mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: warning
ipv6: false

dns:
  enable: false

proxies:
  - name: "HK-01"
    type: vmess
    server: owo-i-n2-auto-p26.yajces.com
    port: 25010
    uuid: 4190b003-4c11-4509-9fa3-57d32372a00e
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    udp: true
    ws-opts:
      path: /zdl/h/dc/1
      headers:
        Host: netease.com

  - name: "HK-02"
    type: vmess
    server: owo-i-n2-auto-p56.yajces.com
    port: 55010
    uuid: 4190b003-4c11-4509-9fa3-57d32372a00e
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    udp: true
    ws-opts:
      path: /zdl/h/dc/2
      headers:
        Host: netease.com

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - HK-01
      - HK-02

rules:
  - MATCH,Proxy
